apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerok-langdetector
  labels:
    app: zerok-langdetector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zerok-langdetector
  template:
    metadata:
      name: zerok-langdetector
      labels:
        app: zerok-langdetector
    spec:
      containers:
        - name: zerok-langdetector
          image: rajeevzerok/zerok-langdetector:test
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
      nodeName: kind-worker3
      hostPID: true
