apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
  namespace: zk-client
spec:
  {{- if .Values.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "promtail.selectorLabels" . | nindent 6 }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    {{- include "promtail.podTemplate" . | nindent 4 }}