apiVersion: v1
data:
  config.yaml: |
    redis:
      host: redis-master.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      db: 7
    server:
      host: localhost
      port: 8080
kind: ConfigMap
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
  namespace: zk-client

