apiVersion: v1
data:
  config.yaml: |
    redis:
      port: {{ .Values.redis.port }}
      readTimeout: {{ .Values.redis.readTimeout }}
      dbs:
        traces: {{ .Values.redis.dbs.traces }}
        otel: {{ .Values.redis.dbs.otel }}
        scenarios: {{ .Values.redis.dbs.scenarios }}
        imageStore: {{ .Values.redis.dbs.imageStore }}
    server:
      host: localhost
      port: 8080
kind: ConfigMap
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
  namespace: zk-client

