---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
  namespace: zk-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
rules:
- apiGroups:
  - ""
  - v1
  resources:
  - pods
  verbs:
  - create
  - get
  - delete
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: zk-daemonset
  name: zk-daemonset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zk-daemonset
subjects:
- kind: ServiceAccount
  name: zk-daemonset
  namespace: zk-client
---