apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zk-daemonset
  namespace: zk-client
  labels:
    app: zk-daemonset
spec:
  selector:
    matchLabels:
      app: zk-daemonset
  template:
    metadata:
      name: zk-daemonset
      labels:
        app: zk-daemonset
    spec:
      serviceAccountName: zk-daemonset
      volumes:
        - name: daemonset-config
          configMap:
            name: zk-daemonset
      containers:
        - name: zk-daemonset
          image: zk-daemonset:1.0
          imagePullPolicy: Never
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ZK_REDIS_PASSWORD # Setting Redis password from Secret
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: ZK_REDIS_HOST # Setting Redis password from Secret
              valueFrom:
                configMapKeyRef:
                  name: zk-redis-config
                  key: redisHost
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
          volumeMounts:
            - name: daemonset-config
              mountPath: /zk/config
      hostPID: true
---

apiVersion: v1
data:
  config.yaml: |+
    redis:
      host: redis-master.zk-client.svc.cluster.local
      port: 6379
      readTimeout: 20
      db: 7
    server:
      host: localhost
      port: 8080
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-daemonset
