apiVersion: v1
kind: ServiceAccount
metadata:
  name: zk-daemonset
  labels:
    app: zk-daemonset

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zk-daemonset
  labels:
    app: zk-daemonset
rules:
- apiGroups: ["","v1"]
  resources: ["pods"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]
- apiGroups: ["","v1"]
  resources: ["services"]
  verbs: ["create", "get", "delete", "list", "patch", "update", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zk-daemonset
  labels:
    app: zk-daemonset
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zk-daemonset
subjects:
- kind: ServiceAccount
  name: zk-daemonset
